# Project Information
site_name: 一些可有可无的故事
site_url: https://krlite.github.io/BrokenThoughts/
strict: false

# Contents
nav:
  - 主页: index.md
  - 学习笔记:
    - 杂谈: notebook/index.md
    - 语言探索:
      - Java:
        - 类:
          - 注解: notebook/languages/java/annotation.md
        - 语法:
          - 流式处理: notebook/languages/java/stream.md
          - Lambda 表达式: notebook/languages/java/lambda.md
        - 程序设计:
          - 抽象语法树: notebook/languages/java/ast.md
    - 算法知识:
      - 排序算法:
        - 基础排序算法集合: notebook/algorithms/sort/general.md
        - 堆排序: notebook/algorithms/sort/heap_sort.md
  - 涂鸦:
    - 時の影: doddles/avatars/tokinokage.md

# Theme
theme:
  name: material
  language: zh
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/octagram
        name: 切换至暗色模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/octagram-outline
        name: 切换至亮色模式
  include_search_page: false
  search_index_only: true
  font:
    text: 'Source Sans'
    code: 'JetBrains Mono'
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    # - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

# Repository
repo_url: https://github.com/KrLite/BrokenThoughts/

# Copyright
copyright: 'Copyright &copy; 2022 - 2023 KrLite'

# Customization
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'
  # - '_static/js/math-csr.js?math-csr'
  # - '_static/js/reload_on_navigation'
  # - 'assets/vendor/mathjax/es5/tex-mml-chtml.js?math-csr'
  # - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml

extra_css:
  # - '_static/css/extra.css?v=14'

# Extensions
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  # - pymdownx.snippets:
  #     check_paths: true
  # - pymdownx.progressbar
  # - pymdownx.smartsymbols
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: math
  #         class: arithmatex
  #         format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  # - pymdownx.tilde
  # - pymdownx.tabbed:
  #     alternate_style: true
