# Project Information
site_name: Material Perfection
site_url: https://krlite.github.io/Material-Perfection/
strict: false

# Contents
nav:
  - 主页: index.md

# Theme
theme:
  name: material
  language: en
  favicon: favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/octagram
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/octagram-outline
        name: Switch to light mode
  include_search_page: false
  search_index_only: true

  # Tips: Relative paths can navigate to svgs under path 'mkdocs-material/material/.icons'
  icon:
    logo: logo
    repo: material/github-alt

  # Tips: currently, the text font is set under 'stylesheets/css/font.css'
  font:
    # text: 'Source Sans'
    code: 'JetBrains Mono'
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant # Do not activate. Will break markdown math renderer.
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

# Repository
repo_url: https://github.com/KrLite/Material-Perfection/
repo_name: KrLite/Material-Perfection

# Copyright
copyright: 'Copyright &copy; 2022 - 2023 KrLite'

# Customization
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML' # Markdown math resolver

extra_css:
  - 'stylesheets/css/extra.css?v=14' # Optimize general appearances
  - 'stylesheets/css/font.css?v=14' # Change the fonts
  - 'stylesheets/css/colored_headings.css?v=14' # Color the headings
  - 'stylesheets/css/oi_wiki.css?v=14' # CSS file from OI Wiki(https://github.com/OI-wiki/OI-wiki)

# Plugins
plugins:
  - search
  - mermaid2

# Extensions
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
     smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
