# Project Information
site_name: 一些可有可无的故事
site_url: https://krlite.github.io/BrokenThoughts/
strict: false

# Contents
nav:
  - 主页: index.md
  - 学习笔记:
    - 语言探索:
      - Java:
        - 类:
          - 注解: notebook/languages/java/annotation
        - 语法:
          - 流式处理: notebook/languages/java/stream
          - Lambda 表达式: notebook/languages/java/lambda
        - 程序设计:
          - 抽象语法树: notebook/languages/java/ast
    - 算法知识:
      - 排序算法: notebook/algorithms/sort
  - 涂鸦:
    - 時の影: doddles/avatars/tokinokage

# Theme
theme:
  name: material
  language: zh
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/octagram
        name: 暗色模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/octagram-outline
        name: 亮色模式
  font:
    text: 'Source Sans'
    code: 'JetBrains Mono'
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

# Repository
repo_url: https://github.com/KrLite/BrokenThoughts/

# Copyright
copyright: 'Copyright &copy; 2022 - 2023 KrLite'

# Extensions
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
